### PR TITLE
chore: upgrade to hyper 1.0

### PR DESCRIPTION
**Pull request by boxdot**
# Description

Also remove the dependency on hyper-alpn. There is no need for this dependency since all its features are already implemented in hyper-rustls.

Upgrade to remove duplicated dependencies:
* base64 from 0.21 -> 0.22
* pem 1.0 -> 3.0
* ring 0.16 -> 0.17

## How Has This Been Tested?

* Tested manually with the token example

## Due Dilligence

* [x] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by chris13524 — APPROVED** [review]
Thanks for the PR! Sorry about the delay, this repo wasn't being watched but now it is.

**Review by geekbrother — DISMISSED** [review]
Thanks a lot!

**Comment by chris13524** [comment]
Hey @boxdot can you resolve merge conflicts? 🙏  Looks like you just need to add `tcp` feature to `hyper` dependency. Didn't want to commit to your master branch

**Comment by boxdot** [comment]
Sure. I do it today in the evening. Thanks for telling.Am 17.04.2024 18:54 schrieb Chris Smith ***@***.***>:
Hey @boxdot can you resolve merge conflicts? 🙏  Looks like you just need to add tcp feature to hyper dependency. Didn't want to commit to your master branch

**Comment by boxdot** [comment]
> Sure. I do it today in the evening. Thanks for telling.

Sometimes "in the evening" means "one week later". Sorry about that.

**Review by chris13524 — APPROVED** [review]
Thanks!

**Pull request merged**
